version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u171-jdk
    steps:
      - checkout
      - restore_cache:
          key: circleci-redmine-oauth-{{ checksum "pom.xml" }}
      - run: mvn package -X
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-redmine-oauth-{{ checksum "pom.xml" }}
      - store_artifacts:
          path: target/redmine-oauth.hpi

